// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/kaige0207/Go-000/Week05/account/internal/dao"
	"github.com/kaige0207/Go-000/Week05/account/internal/service"
)

// Injectors from wire.go:

func initService() service.UserService {
	userDao := NewUserDao()
	userService := NewUserService(userDao)
	return userService
}

// wire.go:

func NewUserService(dao2 dao.UserDao) service.UserService {
	return service.UserService{
		UserDao: &dao2,
	}
}

func NewUserDao() dao.UserDao {
	return dao.UserDao{}
}
